/*
    This is an autogenerated class any manual edits to this file will be lost the next time this class is generated
    This file was last generated on 12/28/2016 9:56:56 AM from the Assembly: T4Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
*/
namespace T4Test.Dto
{
    //ROOT ENTITIES
    public class TestRootEntityDto
    {
        string StringProperty {get; set;}
        int IntProperty {get; set;}
        System.DateTime CreateDate {get; set;}
        string ShortCreateDate {get; set;}
        TestChildDependencyDto ComplexType {get; set;}
    }


    //DEPENDENCIES
    public class TestChildDependencyDto
    {
        string Name {get; set;}
        string foo {get; set;}
        TestChildChildDependencyDto ChildOfAChild {get; set;}
    }
    public class TestChildChildDependencyDto
    {
        string blah {get; set;}
    }
}